### ISSUE TITLE
Syntax error on launch

### ISSUE THREAD

**Issue by Vankerkom** [CCDirectLink/CCdiscord#3]
The mod does not load properly, it triggers an syntax error.

`Uncaught SyntaxError: Unexpected token ILLEGAL /C:/Program%20Files%20(x86)/Steam/steamapps/common/CrossCode/assets/mods//discord/mod.js:48`

I downloaded the master and inserted the files inside my CrossCode root folder.

**Comment by omegalink12** [comment]
Fixed by installing CCLoader

**Comment by 2767mr** [comment]
Actually solved by updating nwjs
