### ISSUE TITLE
Changing map triggers error

### ISSUE THREAD

**Issue by Vankerkom** [CCDirectLink/CCdiscord#5]
The mod works fine when in the menu but when I change a map, the console output the following stack-trace:

> Uncaught TypeError: Cannot read property 'split' of undefined
    at setActivity (mod.js:47)

CCLoader Hash: be74eee13a8da216263f2313681363fadbe4a711
CrossCode: 1.0.0-8

**Comment by ghost** [comment]
Please provide the map name, version of CCLoader, and version of CrossCode.

**Comment by omegalink12** [comment]
This sounds like an error with ccloader / simplify. I can't think of a
valid reason for getmapname to return undefined.
Temp fix would be to check for undefined and replace with ""

**Comment by Vankerkom** [comment]
CCLoader Hash: be74eee13a8da216263f2313681363fadbe4a711
CrossCode: 1.0.0-8

**Comment by ghost** [comment]
This is an issue with an old version that should no longer been issue with the lastest version.
